import numpy as np


class Connector:

    @classmethod
    def connect(cls,
                time_array: np.ndarray,
                open_circuit_voltage_array: np.ndarray,
                source_impedance: float,
                load_impedance: float,
                signal_baseline:float = 0.0) -> tuple[np.ndarray, np.ndarray]:
        
        """
        Apply the load of a component the to the open circut voltage of the preceding component without account for cable attenuation 
        
        Args:
            time_array (np.ndarray): Array of signal's time values in seconds.
            open_volts_array (np.ndarray): Corresponding open circuit voltage values at each time bin in time_array. Generated by the preceding component 
            source_impedance (float): Impedance of the signal source (preceding component).
            load_impedance (float): Impedance of the component .
            signal_baseline (float): Signal baseline. May be 0.0 or a DC offset 
        Return:
            time_array (np.ndarray): original time array.
            loaded_voltage_array (np.ndarray): Array of voltage values after the load has been applied

        """
        
        pulse_voltage = open_circuit_voltage_array - signal_baseline

        if np.isinf(load_impedance):
            load_factor = 1.0
        else:
            load_factor = load_impedance / ( source_impedance + load_impedance)
        
        loaded_voltage_array = ( signal_baseline + pulse_voltage * load_factor )

        return time_array, loaded_voltage_array